name: chateo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  cloud_firestore: ^3.1.8
  equatable: ^2.0.3
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_staggered_animations: ^1.0.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.3.1
  logger: ^1.1.0
  hydrated_bloc: ^8.0.0
  pin_code_fields: ^7.3.0
  flutter_svg: ^1.0.3
  file_picker: ^4.3.3
  firebase_storage: ^10.2.7
  open_file: ^3.2.1
  path_provider: ^2.0.9
  

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/

